function createfigure(xvector1, ymatrix1)
%CREATEFIGURE(XVECTOR1, YMATRIX1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 08-Feb-2018 09:19:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1);
set(bar1(2),'DisplayName','sinusoiida','FaceColor',[0 0 0]);
set(bar1(1),'DisplayName','kosinusoiida',...
    'FaceColor',[0.831372559070587 0.815686285495758 0.7843137383461]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline',...
    'String','tekst ko ieliksim ar peles paliidziibu',...
    'Position',[0.483288770053476 0.709580838323354 0]);

% Create xlabel
xlabel('t,s');

% Create title
title('Mans pirmais grafiks');

% Create ylabel
ylabel('U,V');

box(axes1,'on');
grid(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.523059736300056 0.682923655709767 0.120207251569768 0.0898437476716937]);

